pjt-django/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

pjt-django/final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('quizzes/', include('quizzes.urls')),
]

pjt-django/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/review/', views.create_review, name='create_review'),
]

pjt-django/quizzes/urls.py
from django.urls import path
from django.urls import URLPattern
from . import urls_single
from . import urls_recration
from .views import views

app_name = 'quizzes'

urlpatterns = [
    path('', views.index, name='index'),
]

urlpatterns += urls_single.urlpatterns
urlpatterns += urls_recration.urlpatterns

pjt-django/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Actor(models.Model):
    actor_id = models.IntegerField()
    name = models.CharField(max_length=100)
    name_kr = models.CharField(max_length=100)


class Director(models.Model):
    director_id = models.IntegerField()
    name = models.CharField(max_length=100)
    name_kr = models.CharField(max_length=100)


class Movie(models.Model):
    movie_id = models.IntegerField()
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100)
    backdrop_path = models.CharField(max_length=30)
    poster_path = models.CharField(max_length=30)
    trailer_path =  models.CharField(max_length=30)
    release_date = models.DateField()
    vote_average = models.FloatField()
    original_language = models.CharField(max_length=5)
    overview = models.TextField()
    directors = models.ManyToManyField(Director, related_name='movies')
    actors = models.ManyToManyField(Actor, related_name='movies')


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    content = models.CharField(max_length=50)

pjt-django/movies/forms.py
from .models import Review
from django import forms

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ('content',)
        widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control', 'cols': 200, 'placeholder':'여기에 댓글을 작성해 주세요',})
        }

pjt-django/movies/views.py
from platform import release
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods, require_GET, require_POST

from .models import Movie, Actor, Director, Review
from .forms import ReviewForm
from packages.movies import youtube, naver

def get_trailers(movies):
    for movie in movies:
        if movie.trailer_path == '':
            movie.trailer_path = youtube.youtube_search_trailer(movie.original_title, movie.original_language == 'ko')
            movie.save()
    return

def get_name_kr(names):
    for name in names:
        if name.name_kr == '':
            name.name_kr = naver.papago(name.name, 'en', 'ko')['message']['result']['translatedText']
            name.save()
    return


@require_http_methods(['GET', 'POST'])
def index(request):
    if request.method == 'POST':
        # 관리자만 접근 가능 + 새로운 영화 목록 추가
        return
    else:
        movies = Movie.objects.order_by('-release_date')[:10]    # 반환할 movie list 수정 필요
        get_trailers(movies)

    context = {
        'movies': movies,
    }
    
    return render(request, 'movies/index.html', context)


@require_GET
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk = movie_pk)
    
    actors = movie.actors.all()[:5]
    directors = movie.directors.all()[:2]
    reviews = movie.review_set.all()

    actor_movies, director_movies = Movie.objects.none(), Movie.objects.none()
    # 관련 영화에서 detail 영화는 제거하기
    for actor in actors:
        actor_movies |= actor.movies.all()
    for director in directors:
        director_movies |= director.movies.all()
    
    actor_movies = actor_movies.exclude(pk = movie_pk).distinct()
    director_movies = director_movies.exclude(pk = movie_pk).distinct()
    
    get_trailers(actor_movies)
    get_trailers(director_movies)

    if movie.original_language == 'ko':
        get_name_kr(actors)
        get_name_kr(directors)
    form = ReviewForm()

    form = ReviewForm()

    context = {
        'movie': movie,
        'actors': actors,
        'directors': directors,
        'actor_movies': actor_movies,
        'director_movies': director_movies,
        'reviews': reviews,
        'review_form': form,

    }
        
    return render(request, 'movies/detail.html', context)


@require_POST
def create_review(request, movie_pk):
    # 로그인한 사용자만 접근하도록 허용하기

    movie = get_object_or_404(Movie, pk=movie_pk)
    form = ReviewForm(request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        review.movie = movie
        review.user = request.user
        review.save()
    return redirect('movies:detail', movie.pk)


# review 수정 및 삭제 구현

pjt-django/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load static %}


{% block style %}

{% endblock  %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<head>
  <div style="height: 50px;"></div>
</head>
<div class="container-xxl p-3 bg-dark bg-opacity-75 rounded mt-5">
  <div class="row">
    <div class="col-sm-5">
      <img src={{ "https://www.themoviedb.org/t/p/w300_and_h450_bestv2"|add:movie.poster_path }} class="card-img img-thumbnail p-2 rounded" alt="영화 포스터">
    </div>
    <div class="col-sm-7">      
      <h2 class="mb-4 p-3 bg-dark text-white bg-gradient">{{ movie.title }}</h2>
      <div class="ms-3 me-5">
        <p class="p-1 bg-white text-dark bg-opacity-25 fw-bold rounded">개봉 : {{ movie.release_date}}</p>
        <p class="p-1 bg-white text-dark bg-opacity-25 fw-bold rounded">TMDB 평점 : {{ movie.vote_average }}</p> 
        
        <p class="p-1 bg-white text-dark bg-opacity-25 fw-bold rounded">감독 :
          {% for director in directors  %}  
          {{ director.name_kr }} 
          {% endfor %}
        </p>               
        <p class="p-1 bg-white text-dark bg-opacity-25 fw-bold rounded">출연 :
          {% for actor in actors  %} 
          {{ actor.name_kr }}
          {% endfor %} 
        </p>
        <p class="fw-bold p-1 bg-white text-dark bg-opacity-25 rounded ">줄거리</p>    
        <p class="bg-white text-dark bg-opacity-50 p-1 rounded">{{ movie.overview }}</p>
        <div>
          <p class="mb-3 fw-bold p-1 bg-white text-dark bg-opacity-25 rounded">예고편</p>   
          <div class="ratio ratio-16x9 " style="width: 400px;">          
            <iframe class="ratio bg-white p-2 rounded"  width="560" height="315" src={{"https://www.youtube.com/embed/"|add:movie.trailer_path }} frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
          </div>   
        </div>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="container-xxl p-3 bg-dark bg-opacity-75 rounded">
  <div class="row">
    <div class="col me-4">
      <h5 class="mt-3 fw-bold mb-4 p-3 bg-dark text-white bg-gradient">감독의 관련 영화</h5>      
      <div class="row row-cols-1  row-cols-md-2  row-cols-xl-3 row-cols-xxl-4 mt-3">
          {% for director_movie in director_movies %} 
            <div class="main-container col mb-2">
              <div class="img-container card bg-dark text-white" style="width: 10rem;">          
                <img src={{ "https://www.themoviedb.org/t/p/w300_and_h450_bestv2"|add:director_movie.poster_path }} class="card-img img-thumbnail" alt="포스터 이미지">
                <div class="card-img-overlay d-flex align-items-end justify-content-center">                  
                  <a class="text-reset card-title fw-bold text-decoration-none fs-4" href="{% url 'movies:detail' director_movie.pk %}">{{ director_movie.title }}</a>                  
                </div>
              </div>
            </div>
          {% endfor %}          
      </div>
    </div>
    <div class="col me-4">
      <h5 class="mt-3 fw-bold mb-4 p-3 bg-dark text-white bg-gradient">배우의 관련 영화</h5>
      <div class="row row-cols-1 row-cols-md-2  row-cols-xl-3 row-cols-xxl-4 mt-3">
        {% for actor_movie in actor_movies  %}
          <div class="main-container col mb-2">
            <div class="img-container card bg-dark text-white" style="width: 10rem;">          
              <img src={{ "https://www.themoviedb.org/t/p/w300_and_h450_bestv2"|add:actor_movie.poster_path }} class="card-img img-thumbnail" alt="포스터 이미지">
              <div class="card-img-overlay d-flex align-items-end justify-content-center">                  
                <a class="text-reset card-title fw-bold text-decoration-none fs-4" href="{% url 'movies:detail' actor_movie.pk %}">{{ actor_movie.title }}</a>                  
              </div>
            </div>
          </div>
        {% endfor %}   
      </div>
    </div>
  </div>
  
</div>
<hr>
<div class="container-xxl p-3 bg-dark bg-opacity-75 rounded">
  <div class="row">
    <h4 class="p-3 bg-dark text-white bg-gradient ms-3"  style="width: 97%;">Reviews</h4>
    <div class="review_create_list mt-3 mb-3">
      {% if request.user.is_authenticated %}
        <form action="{% url 'movies:create_review' movie.pk %}" method="POST" class="d-flex align-items-center ms-3">
          {% csrf_token %}
          {{ review_form.content }}
          <input class="btn btn-dark ms-3" style="height: 50px; width:auto;" type="submit">
        </form>
      {% else %}
        <p class="fw-bold mt-3 ms-3 bg-white text-dark rounded p-2 col-8 col-sm-6 col-md-4 col-xl-3  mb-5">
          <a href="{% url 'accounts:login' %}" class="text-decoration-none text-reset">댓글을 작성하려면 [로그인]하세요.</a>
        </p>          
      {% endif %}
    </div>  
    <hr>    
    {% if reviews|length %}
      <p class="fw-bold ms-4 bg-white text-dark rounded p-2 col-1 col-sm-1 col-md-1 col-xl-1" >댓글({{ reviews|length }})</p>
    {% endif %}    
    <hr>
    <div class="review_list mb-5 mt-3 ms-4 bg-white text-dark rounded" style="width: 95%;">
      {% for review in reviews %}
        <div class="ms-3 mt-3">
          {{ review.user }} : {{ review.content }}
          <hr>
        </div>
      {% empty %}
        <p class="mt-3"><b>댓글이 없어요..</b></p>
      {% endfor %}
    </div>
  </div>
</div>
<footer>
  <div class="mt-5"></div>
</footer>
<a style="position:fixed; bottom:30px; right:30px; z-index: 30;" href="{% url 'quizzes:index'%}" class="bg-warning rounded-circle" >
  <img src="https://kcoupet.com/assets/img/sideMenu/index_hambg_icon12.png" alt="퀴즈 이미지" style="width: 110px;">
</a>

{% endblock %}

pjt-django/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock  %}

{% block content %}
<body> 
  <div class="text-center mb-5 mt-3">    
    <img class="ratio mt-5" src="{% static 'logo-img/main-logo.png' %}" alt="메인 페이지 이미지" style="width: 95%;">
  </div>  
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-5 ms-4">      
      {% for movie in movies  %}  
        <div class="main-container col mb-4">
          <div class="img-container card bg-dark text-white" style="width: 17rem;">    
            <img src={{ "https://www.themoviedb.org/t/p/w300_and_h450_bestv2"|add:movie.poster_path }} class="card-img img-thumbnail" alt="포스터 이미지">
            <div class="card-img-overlay d-flex align-items-end justify-content-center">              
              <button class="play-btn video-btn" data-bs-toggle="modal" data-bs-target="#exampleModal{{movie.pk}}">
                <i class="bi bi-play-circle fs-1" 
                style="text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;"
                data-toggle="tooltip" 
                data-placement="top" 
                title="예고편 보기"
                >
              </i></button>     
              <a 
              class="text-reset card-title fw-bold text-decoration-none fs-4" 
              href="{% url 'movies:detail' movie.pk %}"
              data-toggle="tooltip" 
              data-placement="top" 
              title="자세히 보기"
              >
              {{ movie.title }}
            </a>
          </div>
        </div>          
      </div>    
      {% comment %} Modal {% endcomment %}
      <div class="modal fade bg-dark bg-opacity-75" id="exampleModal{{movie.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header bg-warning text-black ">
              <h5 class="modal-title fs-3" id="exampleModalLabel fw-bold">{{ movie.title }}</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body bg-black text-white">              
              <div class="ratio ratio-16x9">
                <iframe class="embed-responsive-item"  width="560" height="315" src={{"https://www.youtube.com/embed/"|add:movie.trailer_path }} frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
              </div>
            </div>
              <div class="modal-footer bg-warning bg-opacity-25">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a class="btn btn-warning" role="button" href="{% url 'movies:detail' movie.pk %}">Go to Movie Detail</a>
              </div>
            </div>
          </div>
        </div>     
        {% endfor %}
      </div>
    <a style="position:fixed; bottom:30px; right:30px; z-index: 30;" href="{% url 'quizzes:index'%}" class="bg-warning rounded-circle" >
      <img src="https://kcoupet.com/assets/img/sideMenu/index_hambg_icon12.png" alt="퀴즈 이미지" style="width: 110px;">
    </a>

<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% comment %} 모달이 닫힐때 영상이 멈추도록 구성 {% endcomment %}
<script>
  $(function(){
    $('.modal').on('hidden.bs.modal', function (e) {
      $iframe = $(this).find("iframe");
      $iframe.attr("src", $iframe.attr("src"));
    });
  });
</script>
</body>
{% endblock %} 