pjt-django/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

pjt-django/final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('quizzes/', include('quizzes.urls')),
]

pjt-django/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/review/', views.create_review, name='create_review'),
]

pjt-django/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

pjt-django/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', )
        exclude= ('password',)        
        # 회원 정보 변경시 필드 고려하기
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):        
        model = get_user_model()
        fields = UserCreationForm.Meta.fields  
      

pjt-django/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            messages.add_message(request, messages.INFO, '로그인되었습니다.')
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
        messages.add_message(request, messages.ERROR, '로그아웃되었습니다.')
    return redirect('movies:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form =CustomUserCreationForm()
    
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method =="POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)

    context = {
        'form' : form,
    }
    return render(request, 'accounts/change_password.html', context)

pjt-django/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<head class="mb-5">
  <div class="mb-5"></div>
</head>
<div class="ms-5 mt-5">  
  <h1 class="mb-3 ">비밀번호변경</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <h4 class="mt-3">기존 비밀번호 : 기존 비밀번호를 입력해 주세요.</h4>
    {{form.old_password}}
    <h4 class="mt-3">새로운 비밀번호 : 새로운 비밀번호를 입력해 주세요.</h4>    {{form.new_password1}}
    <div class="ms-3 mt-2">
      <p class="text-danger">!주의</p>
      <p>다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.</p>
      <p>비밀번호는 최소 8자 이상이어야 합니다.</p>
      <p>통상적으로 자주 사용되는 비밀번호는 사용할 수 없습니다.</p>
      <p>숫자로만 이루어진 비밀번호는 사용할 수 없습니다.</p>
    </div>
    <h4 class="mt-3">새로운 비밀번호 확인 : </h4>    {{form.new_password2}}  
    <br>      
    <button class="btn btn-dark mt-5">비밀번호 변경하기</button>
  </form>
</div>
{% endblock content %}

pjt-django/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<head>
  <div style="height: 70px;"></div>
</head>
<div class="ms-5 mt-5">  
  <h1 class="mb-3">LogIn</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <h4 class="mt-3">Username : </h4>    {{ form.username }}
    <h4 class="mt-3">Password  : </h4>    {{ form.password }}   
    <br> 
    <button class="btn btn-dark mt-5">LOGIN</button>
  </form>
</div>
{% endblock content %}

pjt-django/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<head>
  <div style="height: 70px;"></div>
</head>
<div class="ms-5 mt-5">
  <h1 class="mb-3">SIGNUP</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <h4 class="mt-3">Username : 150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.</h4>    {{ form.username }}
    <h4 class="mt-3">비밀번호 : 비밀번호를 입력해 주세요.</h4>    
    {{ form.password1 }}
    <div class="ms-3 mt-2">
      <p class="text-danger">!주의</p>
      <p>다른 개인 정보와 유사한 비밀번호는 사용할 수 없습니다.</p>
      <p>비밀번호는 최소 8자 이상이어야 합니다.</p>
      <p>통상적으로 자주 사용되는 비밀번호는 사용할 수 없습니다.</p>
      <p>숫자로만 이루어진 비밀번호는 사용할 수 없습니다.</p>
    </div>
    <h4 class="mt-3">비밀번호 확인 : 비밀번호 확인을 위해 이전과 동일한 비밀번호를 입력하세요. </h4>    
    {{ form.password2 }}    
    <br>
    <button class="btn btn-dark mt-5">SIGNUP</button>
  </form>
</div>
{% endblock content %}

pjt-django/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<head>
  <div style="height: 70px;"></div>
</head>
<div class="ms-5 mt-5">
  <h1 class="mb-3 ">회원정보수정</h1>
  <form action="" method="POST">
    {% csrf_token %}    
      <div class="col-md-2">
        <label for="validationCustom01" class="form-label">First name</label>
        {{ form.first_name }}
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>
      <div class="col-md-2">
        <label for="validationCustom02" class="form-label">Last name</label>
        {{ form.last_name }}
        <div class="valid-feedback">
          Looks good!
        </div>
      </div>
      <div class="col-md-2">
        <label for="validationCustomUsername" class="form-label">Username</label>
        <div class="input-group has-validation">
          <span class="input-group-text" id="inputGroupPrepend">@</span>
          {{ form.username }}
          <div class="invalid-feedback">
            Please choose a username.
          </div>     
        </div>
      </div>
      <div class="mb-3 col-md-4">
        <label for="exampleFormControlInput1" class="form-label">Email address</label>
          {{ form.email}}
      </div>             
    <br>
    <a class="btn btn-secondary mt-5" role="button" href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
    <button class="btn btn-dark mt-5">회원정보 수정하기</button>
    </form>
</div>
{% endblock content %}