pjt-django/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

pjt-django/final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('quizzes/', include('quizzes.urls')),
]

pjt-django/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/review/', views.create_review, name='create_review'),
]

pjt-django/quizzes/urls.py
from django.urls import path
from django.urls import URLPattern
from . import urls_single
from . import urls_recration
from .views import views

app_name = 'quizzes'

urlpatterns = [
    path('', views.index, name='index'),
]

urlpatterns += urls_single.urlpatterns
urlpatterns += urls_recration.urlpatterns

pjt-django/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">    
    <link type="text/css" rel="stylesheet" href="https//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext"  >
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js"></script>
    <title>Movies</title>
    {% block style %}
    {% endblock %}
  </head>
  <body class="bg-warning bg-opacity-25">

    <!-- Example Code -->
    
    <nav class="navbar navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'movies:index'%}">
          <img src="{% static 'logo-img/main-logo.png' %}" class="card-img-top" alt="nav-logo" height="40">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">          
          <div class="offcanvas-header flex-column bg-black bg-opacity-75 text-white">
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            {% if user.is_authenticated %}          
            <h5 class="offcanvas-title fs-1 mt-5" id="offcanvasNavbarLabel">Hello, {{ user.username }}</h5>
            {% else %}      
            <h6 class="offcanvas-title fs-1 mt-5" id="offcanvasNavbarLabel">Please, Login</h6>      
            {% endif %}
          </div>          
          <div class="offcanvas-body bg-warning bg-opacity-25 ">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 ">
              {% if user.is_authenticated %}  
              <li class="nav-item">
                <form action="{% url 'accounts:update' %}" method="GET">
                  {% csrf_token %}
                  <input class="bg-transparent text-dark border-0 text-start"type="submit" value="회원정보 수정">
                </form>
              </li>                
              <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input class="bg-transparent text-dark border-0 text-start"type="submit" value="Logout">
              </form>
              <hr>
              {% else %} 
              <li class="nav-item nav-item mb-3">
                <a class="nav-link active text-dark text-decoration-none" aria-current="page" href="{% url 'accounts:signup' %}" style="margin-left: 5px;">Sign Up</a>
              </li>
              <li class="nav-item nav-item ">
                <a class="nav-link active text-dark text-decoration-none" aria-current="page" href="{% url 'accounts:login' %}" style="margin-left: 5px;">Login</a>
              </li>
              <hr>
              {% endif %}             
              <li class="nav-item mb-3">
                <a class="nav-link active text-dark" aria-current="page" href="{% url 'movies:index'%}" style="margin-left: 5px;">Home</a>
              </li>        
              <li class="nav-item ">
                <a class="nav-link active text-dark" aria-current="page" href="{% url 'quizzes:index'%}" style="margin-left: 5px;">Quiz</a>
              </li>                    
            </ul>            
          </div>
        </div>
      </div>
    </nav>        
    <div></div>
 
    {% block content %}
    {% endblock content %}
    <script src="https//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
    <script src="https//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.js"></script>
    <script src="https//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    
    {% block script %}
    {% endblock script %}
  </body>
</html>