pjt-django/final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('quizzes/', include('quizzes.urls')),
]

pjt-django/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/review/', views.create_review, name='create_review'),
]

pjt-django/quizzes/urls.py
from django.urls import path
from django.urls import URLPattern
from . import urls_single
from . import urls_recration
from .views import views

app_name = 'quizzes'

urlpatterns = [
    path('', views.index, name='index'),
]

urlpatterns += urls_single.urlpatterns
urlpatterns += urls_recration.urlpatterns

pjt-django/quizzes/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

# Create your models here.
class Quiz(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=100)


class QuizPlay(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    answer_list = models.ManyToManyField(Movie, related_name='answers')
    choice_list = models.ManyToManyField(Movie, related_name='choices')
    current = models.IntegerField()
    result_list = models.JSONField()
    

pjt-django/quizzes/forms.py
from django import forms

pjt-django/quizzes/views/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods, require_GET, require_POST

from movies.models import Movie, Actor, Director, Review
from packages.movies import youtube, naver


@require_http_methods(['GET'])
def index(request):    
    return render(request, 'quizzes/index.html')

pjt-django/quizzes/views/views_recration.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods, require_GET



@require_http_methods(['GET'])
def index(request):    
    return render(request, 'quizzes/recration/index.html')

pjt-django/quizzes/views/views_single.py
from operator import length_hint
import random

from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_GET
from django.contrib.auth.decorators import login_required

from movies.models import Movie, Director
from ..models import Quiz, QuizPlay
from packages.movies import naver

@require_http_methods(['GET'])
def index(request):
    quizzes = Quiz.objects.all()
    context = {
        'quizzes': quizzes,
    }
    return render(request, 'quizzes/single/index.html', context)


def quiz_index(request, quiz_pk):
    quiz = Quiz.objects.get(pk = quiz_pk)
    example = f'quiz-example/quiz{quiz_pk}_ex.jpg'
    context = {
        'quiz': quiz,
        'example': example, 
    }
    return render(request, 'quizzes/single/quiz_index.html', context)


@login_required
@require_http_methods(['POST', 'GET'])
def quiz_play(request, quiz_pk, quiz_num):
    quiz = Quiz.objects.get(pk = quiz_pk)
    user = request.user
    base_url = 'https://image.tmdb.org/t/p/w600_and_h900_bestv2'

    if request.method == 'POST':
        if quiz_num == 0:
            # 퀴즈 목록을 생성하자
            if QuizPlay.objects.filter(quiz = quiz, user = user):
                quiz_play =  QuizPlay.objects.get(quiz = quiz, user = user)
                quiz_play.delete()

            quiz_play = QuizPlay.objects.create(
                quiz = quiz,
                user = user,
                current  = 0,
                result_list = [0]*10,
            )

            answers = Movie.objects.filter(original_language = 'ko').order_by('?')[:10]
            choices = []
            nums = 0
            while nums < 30:
                choice = Movie.objects.filter(original_language = 'ko').order_by('?')[0]
                if choice in answers or choice in choices:
                    continue
                choices.append(choice)
                nums += 1
    
            for answer in answers:
                quiz_play.answer_list.add(answer)
            for choice in choices:
                quiz_play.choice_list.add(choice)
            return redirect('quizzes:sin_quiz_play', quiz_pk, 1)

        else:
            if 'result' not in request.POST:
                # 답을 꼭 클릭하도록 메시지 띄우기
                return redirect('quizzes:sin_quiz_play', quiz_pk, quiz_num)
            
            result = request.POST['result']
            
            quiz_play =  QuizPlay.objects.get(quiz = quiz, user = user)
            
            quiz_play.result_list = quiz_grading(result, quiz_play, quiz_num, quiz.answer)
            quiz_play.save()
            return  redirect('quizzes:sin_quiz_play', quiz_pk, quiz_num + 1)

    else:
        if quiz_num > 10:

            return redirect('quizzes:sin_quiz_play_result', quiz_pk)

        quiz_play =  QuizPlay.objects.get(quiz = quiz, user = user)
        quiz_play.current = quiz_num
        quiz_play.save()

    choices = random.sample(quiz_choices(quiz_play, quiz, quiz_num), 4)

    quiz_current = {
            'question' : quiz_play.answer_list.all().values_list(quiz.question)[quiz_num-1][0],
            'choices' : choices,
            }
    
    context = {
                'base_url': base_url,
                'quiz_current': quiz_current,
                'quiz_pk': quiz_pk,
                'current': quiz_num,
        }
    page = f'quizzes/single/quiz{quiz_pk}.html'
    return render(request, page, context)


@login_required
@require_GET
def quiz_play_result(request, quiz_pk):
    quiz = Quiz.objects.get(pk = quiz_pk)
    user = request.user
    quiz_play =  QuizPlay.objects.get(quiz = quiz, user = user)
    results = quiz_play.result_list
    answers = quiz_play.answer_list.all()[::]
    corrects, incorrects = [], []
    
    for result, movie in zip(results, answers):
        if result:
            corrects.append(movie)
        else:
            incorrects.append(movie)
    score = len(corrects)*10
    context = {
        'corrects': corrects,
        'incorrects': incorrects,
        'quiz': quiz,
        'score': score,
    }

    return render(request, 'quizzes/single/quiz_result.html', context)


def quiz_grading(result, quiz_play, quiz_num, answer_field):
    answer = quiz_play.answer_list.all().values_list(answer_field)[quiz_num-1][0]
    if answer_field == 'directors':
        director = Director.objects.get(pk = answer)
        answer = director.name_kr
    correct = 1 if answer == result else 0
    results = quiz_play.result_list
    results[quiz_num-1] = correct
    return results


def quiz_choices(quiz_play, quiz, quiz_num):
    choices = [
        *quiz_play.choice_list.all().values_list(quiz.answer)[3*quiz_num-3:3*quiz_num], 
        quiz_play.answer_list.all().values_list(quiz.answer)[quiz_num-1]
        ]
    if quiz.answer ==  'directors':
        tmp = []
        for choice in choices:
            director = Director.objects.get(pk = choice[0])
            if director.name_kr == '':
                    director.name_kr = naver.papago(director.name, 'en', 'ko')['message']['result']['translatedText']
                    director.save()
            tmp.append(director.name_kr)
        choices = tmp

    return choices

pjt-django/quizzes/templates/quizzes/single/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="ms-5" style="margin: 100px auto;">
  <div class="mb-3 d-flex justify-content-center">    
    <img src="{% static 'logo-img/single-logo.png' %}" class="card-img-top ms-5" alt="quiz-logo" style="width: 800px;">
  </div>  
  <div class="container position-absolute top-50 start-50 translate-middle">
    <div class="row flex-column align-items-center">
      {% for quiz in quizzes %}
      <a href="{% url 'quizzes:sin_quiz_index' quiz.pk %}" class="text-decoration-none btn btn-warning btn-lg col-5 my-2 p-4 fs-3">
        {{quiz.title}}
      </a>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}
 

pjt-django/quizzes/templates/quizzes/single/quiz1.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="d-flex flex-column align-items-center" style="margin: 100px auto;">
  <h1 class="mb-3">Quiz  {{current}} </h1>
  <div class="card" style="height:70%">
    <div class="row">
      <div class="col-md-4">
        <img src="{{base_url}}{{quiz_current.question}}" class="img-fluid rounded-start bg-warning p-2" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <ul class="list-group list-group-flush">
              <li class="list-group-item fw-bold border border-warning p-3">
                정답은?? 
              </li>
            <form action="" method="POST">
              {% csrf_token %}
              {% for choice in quiz_current.choices %}
              <li class="list-group-item my-1">
                <label><input type="radio" name="result" value="{{choice.0}}">{{choice.0}}</label>
              </li>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <a href="{% url 'quizzes:sin_index'%}" class="btn btn-secondary mt-3 me-3"> 돌아가기</a>
                <button class="btn btn-success mt-3 ">다음 문제</button>
              </div>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

pjt-django/quizzes/templates/quizzes/single/quiz2.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="d-flex flex-column align-items-center" style="margin: 100px auto;">
  <h1 class="mb-3">Quiz  {{current}} </h1>
  <div class="card" style="height:70%">
    <div class="row">
      <div class="col-md-4">
        <img src="{{base_url}}{{quiz_current.question}}" class="img-fluid rounded-start bg-warning p-2" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <ul class="list-group list-group-flush">
              <li class="list-group-item fw-bold border border-warning p-3">
                정답은?? 
              </li>
            <form action="" method="POST">
              {% csrf_token %}
              {% for choice in quiz_current.choices %}
              <li class="list-group-item my-1">
                <label><input type="radio" name="result" value="{{choice}}">{{choice}}</label>
              </li>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <a href="{% url 'quizzes:sin_index'%}" class="btn btn-secondary mt-3 me-3"> 돌아가기</a>
                <button class="btn btn-success mt-3 ">다음 문제</button>
              </div>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

pjt-django/quizzes/templates/quizzes/single/quiz_index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="ms-5" style="margin: 100px auto;">
  <h1 class="text-center">{{quiz.title}}</h1>
  <p class="fs-4 text-center">{{quiz.description}}</p>
  <div class="container">
    <h3 class="text-center my-3">예시</h3>
    <div class="d-flex justify-content-center"> 
      <img src="{% static example %}" alt="">
    </div>
    <form action="{% url 'quizzes:sin_quiz_play' quiz.pk 0%}" method="POST" class="d-flex justify-content-center mt-3">
      {% csrf_token %}
      <button class="btn btn-warning ms-3 p-5 fs-1 col-4">문제 풀기</button>
    </form>      
    </div>
    <div class="row justify-content-center">
      <a href="{% url 'quizzes:sin_index'%}" class="btn btn-secondary col-2 ms-3 mt-3">뒤로 가기</a>
    </div>
  </div>
  </div>  
</div>

{% endblock %}
 

pjt-django/quizzes/templates/quizzes/single/quiz_result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div class="container">
  <div class="ms-5 row"style="margin: 70px auto;">
  </div >  
    <h1 class="mb-3 text-center fs-1">Quiz Result</h1>
    <p class="fs-3 text-center">
      '{{ score }}'점입니다!!         
      <form action="{% url 'quizzes:sin_quiz_play' quiz.pk 0%}" method="POST" class="d-flex justify-content-center">
        {% csrf_token %}
        <a href="{% url 'quizzes:sin_index'%}" class="btn btn-secondary">돌아가기</a>
        <button class="btn btn-warning ms-3">다시 풀기</button>
      </form>
    </p>        
</div>
<h3 class="mx-5 bg-danger bg-opacity-50 p-3 rounded"> 오답!! </h3>
<div class="row row-cols-2 row-cols-sm-3 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 row-cols-xxl-6 mx-5">        
  {% for incorrect in incorrects  %}  
    <div class="main-container col  mt-3 mb-4">
      <div class="img-container card bg-dark text-white" style="width: 13rem;">    
        <img src={{ "https://www.themoviedb.org/t/p/w300_and_h450_bestv2"|add:incorrect.poster_path }} class="card-img img-thumbnail" alt="포스터 이미지">
        <div class="card-img-overlay d-flex align-items-end justify-content-center">  
          <a 
            class="text-reset card-title fw-bold text-decoration-none fs-4" 
            href="{% url 'movies:detail' incorrect.pk %}"
            data-toggle="tooltip" 
            data-placement="top" 
            title="자세히 보기"
            >
              {{ incorrect.title }}
          </a>
        </div>
      </div>          
    </div>        
  {% endfor %}
</div>
<h3 class="mx-5 bg-success bg-opacity-50 p-3 rounded"> 정답!! </h3>
<div class="row row-cols-2 row-cols-sm-3 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 row-cols-xxl-6 mx-5">        
  {% for correct in corrects  %}  
    <div class="main-container col  mt-3 mb-4">
      <div class="img-container card bg-dark text-white" style="width: 13rem;">    
        <img src={{ "https://www.themoviedb.org/t/p/w300_and_h450_bestv2"|add:correct.poster_path }} class="card-img img-thumbnail" alt="포스터 이미지">
        <div class="card-img-overlay d-flex align-items-end justify-content-center">  
          <a 
            class="text-reset card-title fw-bold text-decoration-none fs-4" 
            href="{% url 'movies:detail' correct.pk %}"
            data-toggle="tooltip" 
            data-placement="top" 
            title="자세히 보기"
            >
              {{ correct.title }}
          </a>
        </div>
      </div>          
    </div>        
  {% endfor %}
</div>


{% endblock content%}